In [2]:
#Importando librerías

import tensorflow as tf
import numpy as np

### Creación de tensores

In [3]:
t0 = tf.constant(4)
t0

<tf.Tensor: shape=(), dtype=int32, numpy=4>

In [4]:
t1 = tf.constant([1,3, -2, 5])
t1

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([ 1,  3, -2,  5], dtype=int32)>

In [5]:
t2 = tf.constant([[1,2,3], [0, 1, 0]])
t2

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [0, 1, 0]], dtype=int32)>

Un tensor en tensorflow consta de una arreglo numpy, un tamaño y un tipo. Para aceder a cualquiera de dus elementos se usa punto de la sigiente manera:

In [6]:
print(t2.numpy())
print(t2.shape)
print(t2.dtype)

[[1 2 3]
 [0 1 0]]
(2, 3)
<dtype: 'int32'>


### Algebra de tensores

In [7]:
a = tf.constant([[1,2],[3,4]])
b = tf.constant([[0,1],[3,0]])
c = tf.constant([[1,2,3], [0,0,3]])

print("a = ", a, "\n")
print("b = ", b,"\n")
print("c = ", c)

a =  tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32) 

b =  tf.Tensor(
[[0 1]
 [3 0]], shape=(2, 2), dtype=int32) 

c =  tf.Tensor(
[[1 2 3]
 [0 0 3]], shape=(2, 3), dtype=int32)


In [8]:
# Suma

print(a+b)
print(tf.add(a,b))

tf.Tensor(
[[1 3]
 [6 4]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[1 3]
 [6 4]], shape=(2, 2), dtype=int32)


In [9]:
# Multiplicación componente a componente.

print(a*b)
print(tf.multiply(a,b))

tf.Tensor(
[[0 2]
 [9 0]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[0 2]
 [9 0]], shape=(2, 2), dtype=int32)


In [10]:
# Multiplicación de matrices (matricial)

print(a@c)
print(tf.matmul(a,c))

tf.Tensor(
[[ 1  2  9]
 [ 3  6 21]], shape=(2, 3), dtype=int32)
tf.Tensor(
[[ 1  2  9]
 [ 3  6 21]], shape=(2, 3), dtype=int32)


### Funciones de reducción

In [11]:
d = tf.constant(0.5-c.numpy())

print("d = ", d)

d =  tf.Tensor(
[[-0.5 -1.5 -2.5]
 [ 0.5  0.5 -2.5]], shape=(2, 3), dtype=float64)


In [12]:

print("Máx de d: ", tf.reduce_max(d).numpy(),"\n")
print("Mín de d: ", tf.reduce_min(d).numpy(),"\n")
print("Media de d: ", tf.reduce_mean(d).numpy(),'\n')
print("Arg máx de d: ", tf.argmax(d).numpy(),'\n')
print("Soft máx de d: ", tf.nn.softmax(d).numpy(),'\n')
print("Suma de d: ", tf.reduce_sum(d).numpy())


Máx de d:  0.5 

Mín de d:  -2.5 

Media de d:  -1.0 

Arg máx de d:  [1 1 0] 

Soft máx de d:  [[0.66524096 0.24472847 0.09003057]
 [0.48785555 0.48785555 0.0242889 ]] 

Suma de d:  -6.0


### Indexación y rebanado

In [13]:
# Aceder al elemento de un tensor.

print(d[0,1].numpy(), d[0][1].numpy(),'\n')

print(d[1, 2].numpy(), d[1][2].numpy(), '\n')

-1.5 -1.5 

-2.5 -2.5 



In [14]:
# Acceder a una fila.

print(d[1].numpy(), '\n')

print(d[0].numpy(), '\n')

[ 0.5  0.5 -2.5] 

[-0.5 -1.5 -2.5] 



In [15]:
t = tf.constant(-1.5+ np.array([[1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9]
                   ]))
t

<tf.Tensor: shape=(3, 3), dtype=float64, numpy=
array([[-0.5,  0.5,  1.5],
       [ 2.5,  3.5,  4.5],
       [ 5.5,  6.5,  7.5]])>

In [16]:
# Rebanado en filas.

t[:2]

<tf.Tensor: shape=(2, 3), dtype=float64, numpy=
array([[-0.5,  0.5,  1.5],
       [ 2.5,  3.5,  4.5]])>

In [17]:
t[1:]

<tf.Tensor: shape=(2, 3), dtype=float64, numpy=
array([[2.5, 3.5, 4.5],
       [5.5, 6.5, 7.5]])>

In [18]:
# Rebanado en filas y columnas.

t[1:, 1:]

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[3.5, 4.5],
       [6.5, 7.5]])>

In [19]:
# Seleccionando una columna.

t[:, 1]

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([0.5, 3.5, 6.5])>

### Redimensionar

In [20]:

# Se usa tf.reshape(tensor, tamaño)

t = tf.constant(np.arange(24))
t




<tf.Tensor: shape=(24,), dtype=int64, numpy=
array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])>

In [21]:
tf.reshape(t,(3,8))

<tf.Tensor: shape=(3, 8), dtype=int64, numpy=
array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23]])>

In [22]:
tf.reshape(t, (12,2))

<tf.Tensor: shape=(12, 2), dtype=int64, numpy=
array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23]])>

In [23]:
tf.reshape(t, (2,6,2))

<tf.Tensor: shape=(2, 6, 2), dtype=int64, numpy=
array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17],
        [18, 19],
        [20, 21],
        [22, 23]]])>

In [24]:
# Si se usa -1 en la dimensión, reshape elige el mejor tamaño.

tf.reshape(t, (2,-1,2))

<tf.Tensor: shape=(2, 6, 2), dtype=int64, numpy=
array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17],
        [18, 19],
        [20, 21],
        [22, 23]]])>

In [25]:
tf.reshape(t, (-1,2,4))

<tf.Tensor: shape=(3, 2, 4), dtype=int64, numpy=
array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23]]])>

In [26]:
# En caso de que no se pueda redimensionar una matriz, marca error.

try:
    tf.reshape(t, (2,6))
except:
    print("Error")

Error


In [27]:
try:
    tf.reshape(t, (5, -1))
except:
    print("Error")

Error


### Conversión de tipos

In [28]:
# Se usa la función cast(tensor, dtype= tf.tipo)

t.dtype

tf.int64

In [29]:
tfloat16 = tf.cast(t,dtype=tf.float16)
tfloat16.dtype

tf.float16

In [30]:
tf.cast(tfloat16, dtype=tf.int64)

<tf.Tensor: shape=(24,), dtype=int64, numpy=
array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])>

In [31]:
# En tensorflow, operaciones entre tensores de diferente tipo marca error

try:
    t+tfloat16
except:
    print("Error")

Error


In [32]:
try:
    1.5 -t
except:
    print("Error")

Error


In [33]:
try:
    tl.matmul(t, tfloat16)
except:
    print("Error")

Error


### Radiodibusión (broadcasting)

In [34]:
x = tf.range(3)
y = tf.constant([2,2,2])
z = tf.constant(2)

x

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([0, 1, 2], dtype=int32)>

In [35]:
# Las dimensiones del vector más pequeño de adaptan para poder hacer la operación

x*y

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([0, 2, 4], dtype=int32)>

In [36]:
x*z

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([0, 2, 4], dtype=int32)>

In [38]:
#La función broadcast_to estira las dimensiones del tensor orginal 
#para hacerlas coincidir con las dimensiones dadas

tf.broadcast_to([1,2,3], [3,3])

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]], dtype=int32)>

In [40]:
tf.broadcast_to([[2], [1]], (2,5))

<tf.Tensor: shape=(2, 5), dtype=int32, numpy=
array([[2, 2, 2, 2, 2],
       [1, 1, 1, 1, 1]], dtype=int32)>

### Tensores irregulares

In [41]:
# Para crear tensores irregulares donde las longitudes de las filas o columnas no es constante, 
# se usa la función ragged.constant

e = tf.ragged.constant([[1], [2,2], [3,3,3], [4]])

<tf.RaggedTensor [[1], [2, 2], [3, 3, 3], [4]]>

### Tensores tipo string

In [43]:
tf.constant('hola mundo')

<tf.Tensor: shape=(), dtype=string, numpy=b'hola mundo'>

In [45]:
tf.constant(list("hola mundo"))

<tf.Tensor: shape=(10,), dtype=string, numpy=
array([b'h', b'o', b'l', b'a', b' ', b'm', b'u', b'n', b'd', b'o'],
      dtype=object)>

In [46]:
# Convertir un string a una lista de números

st = tf.constant("1 10 10.4")

print(tf.strings.to_number(tf.strings.split(st, " ")))

tf.Tensor([ 1.  10.  10.4], shape=(3,), dtype=float32)


### Tensores dispersos

In [49]:
#  tensor disperso
st = tf.sparse.SparseTensor(indices = [[0,1], [1,2]],
                             values = [1,2],
                            dense_shape =[3,4])
print(st, "\n")

# convierte a tensor denso
print(tf.sparse.to_dense(st))

SparseTensor(indices=tf.Tensor(
[[0 1]
 [1 2]], shape=(2, 2), dtype=int64), values=tf.Tensor([1 2], shape=(2,), dtype=int32), dense_shape=tf.Tensor([3 4], shape=(2,), dtype=int64)) 

tf.Tensor(
[[0 1 0 0]
 [0 0 2 0]
 [0 0 0 0]], shape=(3, 4), dtype=int32)
